[package]
name = "bevy_pong"
version = "0.1.0"
edition = "2024"

[dependencies]
# bevy = { version = "0.15.3", features = ["dynamic_linking"] }
bevy = { version = "0.15.3" }
rand = "0.9.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
